name: Automated Test

on: [pull_request, workflow_dispatch]

jobs:
  build:
    name: Flutter Format & Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2.3.0

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib

      - name: Analyze
        run: flutter analyze lib

      # - name: Run Tests
      #   run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
